config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#team_info'
  get '/all_users', to: 'visitors#all_users'
  devise_for :users
  resources :users
  resources :seasons do
    resources :games, except: [:index]
  end
  post 'add_players_to_season', to: 'seasons#add_players_to_season'
  resources :players
end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :games
  has_many :statistics, through: :players
  has_and_belongs_to_many :players

  validates_presence_of :year, :wins, :losses
  validates_uniqueness_of :year

  def percentage(wins, losses)
    string = (wins.to_f / (losses+wins).to_f).round(3)
    sprintf('%.3f', string)
  end

  def team_plate_appearances(season = nil)
    season ? statistics.where(season_id: season).sum(:plate_appearance) : statistics.sum(:plate_appearance)
  end

  def team_at_bats(season = nil)
    if season
      plate_appearance = statistics.where(season_id: season).sum(:plate_appearance)
      walks = statistics.where(season_id: season).sum(:walks)
      sac_fly = statistics.where(season_id: season).sum(:sac_fly)
      @total_at_bats = plate_appearance - (walks + sac_fly)
    else
      plate_appearance = statistics.sum(:plate_appearance)
      walks = statistics.sum(:walks)
      sac_fly = statistics.sum(:sac_fly)
      @total_at_bats = plate_appearance - (walks + sac_fly)
    end
  end

  def team_runs(season = nil)
    season ? @team_runs = statistics.where(season_id: season).sum(:runs) : @team_runs = statistics.sum(:runs)
  end

  def team_hits(season = nil)
    season ? @total_hits = statistics.where(season_id: season).sum(:hits) : @total_hits = statistics.sum(:hits)
  end

  def team_doubles(season = nil)
    season ?  @total_doubles = statistics.where(season_id: season).sum(:doubles) : @total_doubles = statistics.sum(:doubles)
  end

  def team_triples(season = nil)
    season ? @total_triples = statistics.where(season_id: season).sum(:triples) : @total_triples = statistics.sum(:triples)
  end

  def team_homers(season = nil)
    season ? @total_homers = statistics.where(season_id: season).sum(:homers) : @total_homers = statistics.sum(:homers)
  end

  def team_rbis(season = nil)
    season ? @total_rbis = statistics.where(season_id: season).sum(:rbis) : @total_rbis = statistics.sum(:rbis)
  end

  def team_walks(season = nil)
    season ? @total_walks = statistics.where(season_id: season).sum(:walks) : @total_walks = statistics.sum(:walks)
  end

  def team_strikeouts(season = nil)
    season ? @total_strikeouts = statistics.where(season_id: season).sum(:strikeouts) : @total_strikeouts = statistics.sum(:strikeouts)
  end

  def team_sac_fly(season = nil)
    season ? @total_sac_flys = statistics.where(season_id: season).sum(:sac_fly) : @total_sac_flys = statistics.sum(:sac_fly)
  end

  def total_bases(season)
    singles = (@total_hits - (@total_doubles + @total_triples + @total_homers))
    @total_bases = singles + (2 * @total_doubles) + (3 * @total_triples) + (4 * @total_homers)
  end

  def team_batting_avg
    string = (@total_hits.to_f / @total_at_bats.to_f).round(3)
    sprintf('%.3f', string)
  end

  def team_on_base_pct
    @on_base_pct = ((@total_hits.to_f + @total_walks.to_f) / (@total_at_bats.to_f + @total_walks.to_f + @total_sac_fly.to_f)).round(3)
    sprintf('%.3f', @on_base_pct)
  end

  def team_slugging_pct
    @slugging_pct = (@total_bases.to_f / @total_at_bats.to_f).round(3)
    sprintf('%.3f', @slugging_pct)
  end

  def team_on_base_plus_slg
    @on_base_plus_slug = @slugging_pct + @on_base_pct
    sprintf('%.3f', @on_base_plus_slug)
  end



end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController

  def index
    @seasons = Season.all
    @games = Game.all
    @statistics = Statistic.all
    @plate_appearances = @statistics.sum(:plate_appearance)
    @at_bats = @statistics.sum(:plate_appearance) - (@statistics.sum(:walks) + @statistics.sum(:sac_fly))
    @runs = @statistics.sum(:runs)
    @hits = @statistics.sum(:hits)
    @singles = @statistics.sum(:hits) - (@statistics.sum(:doubles) + @statistics.sum(:triples) + @statistics.sum(:homers))
    @doubles = @statistics.sum(:doubles)
    @triples = @statistics.sum(:triples)
    @homers = @statistics.sum(:homers)
    @rbis = @statistics.sum(:rbis)
    @walks = @statistics.sum(:walks)
    @strikeouts = @statistics.sum(:strikeouts)
    @sac_fly = @statistics.sum(:doubles)
    @total_bases = @singles + (2 * @doubles) + (3 * @triples) + (4 * @homers)
    @batting_avg = sprintf('%.3f',(@hits.to_f / @at_bats.to_f).round(3))
    @on_base_pct = sprintf('%.3f',((@hits.to_f + @walks.to_f) / (@at_bats.to_f + @walks.to_f + @sac_fly.to_f)).round(3))
    @slugging_pct = sprintf('%.3f',(@total_bases.to_f / @at_bats.to_f).round(3))
    @on_base_plus_slg = sprintf('%.3f', @on_base_pct.to_f + @slugging_pct.to_f)
  end

  def show
    @season = Season.find(params[:id])
    @games = @season.games
    @players = @season.players
  end

  def new
    @season = Season.new
    @years = 1980..2100
    @players = Player.all
    @seasons_players = @season.players
  end

  def create
    @season = Season.create(season_params)
    @season.games.each {|game| game = Game.create(game_params)}
    if @season.save
      redirect_to season_path(@season)
    else
      render :new
    end
  end

  def edit
    @season = Season.find(params[:id])
    @years = 1980..2100
  end

  def update
    @season = Season.find(params[:id])
    if @season.update(season_params)
      redirect_to season_path(@season)
    else
      render :edit
    end
  end

  def destroy
    @season = Season.find(params[:id])
    if @season.destroy
      redirect_to seasons_path
    else
      redirect_to season_path
    end
  end

  def add_players_to_season
    players_added = params["players"].values
  end

  private
  def season_params
    params.require(:season).permit(:year, :wins, :losses, :runs_scored, :runs_allowed, :description)
  end

  def game_params
    params.require(:game).permit(:opponent, :home_score, :opponent_score, :win_result, :date, :home_first_inning, :home_second_inning, :home_third_inning, :home_fourth_inning, :home_fifth_inning, :home_sixth_inning, :home_seventh_inning, :home_ninth_inning, :opponent_first_inning, :opponent_second_inning, :opponent_third_inning, :opponent_fourth_inning, :opponent_fifth_inning, :opponent_sixth_inning, :opponent_seventh_inning, :opponent_eigth_inning, :opponent_ninth_inning)
  end

end

app/views/seasons/_form.html.erb
<% @season.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>

<%= form_for @season do |f| %>

  <%= f.label :year %>
  <%= f.select :year, options_for_select(@years.map{|year| year}) %>

  <%= f.label :wins %>
  <%= f.number_field :wins %>

  <%= f.label :losses %>
  <%= f.number_field :losses %>

  <%= f.label :runs_scored %>
  <%= f.number_field :runs_scored %>

  <%= f.label :runs_allowed %>
  <%= f.number_field :runs_allowed %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/seasons/_season_player_stats.html.erb
<div id="player-stats">
  <div id="header">
    <td><%= @season.year %> Season Stats</td>
  </div>
  <table border="2">
    <thead>
      <td>Name</td>
      <td>#</td>
      <td>Pos</td>
      <td>PA</td>
      <td>AB</td>
      <td>R</td>
      <td>H</td>
      <td>2B</td>
      <td>3B</td>
      <td>HR</td>
      <td>RBI</td>
      <td>BB</td>
      <td>SO</td>
      <td>SF</td>
      <td>TB</td>
      <td>AVG</td>
      <td>OBP</td>
      <td>SLG</td>
      <td>OPS</td>
    </thead>
    <tbody>
      <% @season.players.order(last_name: :asc).each do |player| %>
      <tr>
        <td><%= link_to player.name, player_path(player) %></td>
        <td><%= player.number %></td>
        <td><%= player.primary_position %></td>
        <td><%= player.total_plate_appearance(@season.id) %></td>
        <td><%= player.total_at_bats(@season.id) %></td>
        <td><%= player.total_runs(@season.id) %></td>
        <td><%= player.total_hits(@season.id) %></td>
        <td><%= player.total_doubles(@season.id) %></td>
        <td><%= player.total_triples(@season.id) %></td>
        <td><%= player.total_homers(@season.id) %></td>
        <td><%= player.total_rbis(@season.id) %></td>
        <td><%= player.total_walks(@season.id) %></td>
        <td><%= player.total_strikeouts(@season.id) %></td>
        <td><%= player.total_sac_fly(@season.id) %></td>
        <td><%= player.total_bases(@season.id) %></td>
        <td><%= player.season_batting_avg(@season.id) %></td>
        <td><%= player.on_base_pct(@season.id)  %></td>
        <td><%= player.slugging_pct(@season.id)  %></td>
        <td><%= player.on_base_plus_slg %></td>
      </tr>
      <% end %>
    </tbody>
    <thead>
      <td>Totals</td>
      <td></td>
      <td></td>
      <td><%= @season.team_plate_appearances(@season.id) %></td>
      <td><%= @season.team_at_bats(@season.id) %></td>
      <td><%= @season.team_runs(@season.id) %></td>
      <td><%= @season.team_hits(@season.id) %></td>
      <td><%= @season.team_doubles(@season.id) %></td>
      <td><%= @season.team_triples(@season.id) %></td>
      <td><%= @season.team_homers(@season.id) %></td>
      <td><%= @season.team_rbis(@season.id) %></td>
      <td><%= @season.team_walks(@season.id) %></td>
      <td><%= @season.team_strikeouts(@season.id) %></td>
      <td><%= @season.team_sac_fly(@season.id) %></td>
      <td><%= @season.total_bases(@season) %></td>
      <td><%= @season.team_batting_avg %></td>
      <td><%= @season.team_on_base_pct %></td>
      <td><%= @season.team_slugging_pct %></td>
      <td><%= @season.team_on_base_plus_slg %></td>
    </thead>
  </table>
</div>

app/views/seasons/_season_roster.html.erb
<h2 class="title">Roster</h2>
<table border="2">
  <thead class="pitchers">
    <tr>
      <th>#</th>
      <th>Pitchers</th>
      <th>Bats</th>
      <th>Throws</th>
      <th>Height</th>
      <th>Weight</th>
      <th>DOB</th>
    </tr>
  </thead>
  <tbody>
    <%= render 'players/pitchers' %>
  </tbody>
  <thead class="catchers">
    <tr>
      <th>#</th>
      <th>Catchers</th>
      <th>Bats</th>
      <th>Throws</th>
      <th>Height</th>
      <th>Weight</th>
      <th>DOB</th>
    </tr>
  </thead>
  <tbody>
    <%= render 'players/catchers' %>
  </tbody>
  <thead class="infielders">
    <tr>
      <th>#</th>
      <th>Infielders</th>
      <th>Bats</th>
      <th>Throws</th>
      <th>Height</th>
      <th>Weight</th>
      <th>DOB</th>
    </tr>
  </thead>
  <tbody>
    <%= render 'players/infielders' %>
  </tbody>
  <thead class="outfielders">
    <tr>
      <th>#</th>
      <th>Outfielders</th>
      <th>Bats</th>
      <th>Throws</th>
      <th>Height</th>
      <th>Weight</th>
      <th>DOB</th>
    </tr>
  </thead>
  <tbody>
    <%= render 'players/outfielders' %>
  </tbody>
</table>

app/views/seasons/_season_stats_body.html.erb
<tbody>
  <% @seasons.order(year: :asc).each do |season| %>
    <tr>
      <td><%= season.year %></td>
      <td><%= season.games.count %></td>
      <td><%= season.team_plate_appearances(season.id) %></td>
      <td><%= season.team_at_bats(season.id) %></td>
      <td><%= season.team_runs(season.id) %></td>
      <td><%= season.team_hits(season.id) %></td>
      <td><%= season.team_doubles(season.id) %></td>
      <td><%= season.team_triples(season.id) %></td>
      <td><%= season.team_homers(season.id) %></td>
      <td><%= season.team_rbis(season.id) %></td>
      <td><%= season.team_walks(season.id) %></td>
      <td><%= season.team_strikeouts(season.id) %></td>
      <td><%= season.team_sac_fly(season.id) %></td>
      <td><%= season.total_bases(season) %></td>
      <td><%= season.team_batting_avg %></td>
      <td><%= season.team_on_base_pct %></td>
      <td><%= season.team_slugging_pct %></td>
      <td><%= season.team_on_base_plus_slg %></td>
    </tr>
  <% end %>
</tbody>

app/views/seasons/_season_stats_header.html.erb
<thead>
  <tr>
    <td>Year</td>
    <td>G</td>
    <td>PA</td>
    <td>AB</td>
    <td>R</td>
    <td>H</td>
    <td>2B</td>
    <td>3B</td>
    <td>HR</td>
    <td>RBI</td>
    <td>BB</td>
    <td>SO</td>
    <td>SF</td>
    <td>TB</td>
    <td>AVG</td>
    <td>OBP</td>
    <td>SLG</td>
    <td>OPS</td>
  </tr>
</thead>

app/views/seasons/_team_stats.html.erb
<div id="season-stats">
  <div class="head">
    <td>Team Stats</td>
  </div>
  <table class="season-stat" border="1">
    <%= render 'season_stats_header' %>
    <%= render 'season_stats_body' %>
    <%= render 'total_season_stats' %>
  </table>
</div>

app/views/seasons/_total_season_stats.html.erb
<thead>
  <tr>
    <td>Totals</td>
    <td><%= @games.count %></td>
    <td><%= @plate_appearances %></td>
    <td><%= @at_bats %></td>
    <td><%= @runs %></td>
    <td><%= @hits %></td>
    <td><%= @doubles %></td>
    <td><%= @triples %></td>
    <td><%= @homers %></td>
    <td><%= @rbis %></td>
    <td><%= @statistics.sum(:walks) %></td>
    <td><%= @statistics.sum(:strikeouts) %></td>
    <td><%= @statistics.sum(:sac_fly) %></td>
    <td><%= @total_bases %></td>
    <td><%= @batting_avg %></td>
    <td><%= @on_base_pct %></td>
    <td><%= @slugging_pct %></td>
    <td><%= @on_base_plus_slg %></td>
  </tr>
</thead>

app/views/seasons/edit.html.erb
<%= render 'form' %>
<% if can? :destroy, @player %>
  <%= link_to "Delete", season_path(@season), method: :delete%>
<% end %>

app/views/seasons/index.html.erb
<div class="scrolls">
  <div id="content">
    <% if can? :create, @season %>
      <%= link_to "Add Season", new_season_path %>
    <% end %>
    <h2 class="title">Seasons</h2>
    <table class="season-data" border="2">
      <thead>
        <tr>
          <th>Year</th>
          <th>Wins</th>
          <th>Losses</th>
          <th>RS</th>
          <th>RA</th>
          <th>PCT</th>
        </tr>
      </thead>
      <tbody>
        <% @seasons.order(year: :asc).each do |season| %>
        <tr>
          <th><%= link_to season.year, season_path(season) %></th>
          <th><%= season.wins %></th>
          <th><%= season.losses %></th>
          <th><%= season.runs_scored %></th>
          <th><%= season.runs_allowed %></th>
          <th><%= season.percentage(season.wins, season.losses) %></th>
        </tr>
        <% end %>
      </tbody>
    </table>

    <%= render 'team_stats' %>
  </div>
</div>

app/views/seasons/show.html.erb
<div class="scrolls">
  <div id="content">
    <% if can? :update, @season %>
      <%= link_to "Edit Season", edit_season_path(@season) %>
    <% end %>
    <% if can? :create, @game %>
      <%#= link_to "Add Game", new_season_game_path(season: @season.games.build) %>
    <% end %>
    <h1 class="title">Moonrakers Summer <%= @season.year %> Season</h1>
    <div class="season-description">
      <p>
        <%= @season.description %>
      </p>
    </div>
    <table border="2">
      <thead>
        <tr>
          <th>Date</th>
          <th>Opponent</th>
          <th>Moonrakers Score</th>
          <th>Opponent Score</th>
        </tr>
      </thead>
      <tbody>
        <% @games.each do |game| %>
        <tr>
            <th><%= game.format_date(game.date)%></th>
            <th><%= link_to game.opponent, season_game_path(season_id: game.season_id, id: game.id) %></th>
            <th><%= game.home_score %></th>
            <th><%= game.opponent_score %></th>
          <% end %>
        </tr>
      </tbody>
    </table>
    <%#= render 'season_roster' %>
    <%= render 'season_player_stats' %>
  </div>
</div>