config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#team_info'
  get '/all_users', to: 'visitors#all_users'
  devise_for :users
  resources :users
  resources :seasons do
    resources :games, except: [:index]
  end
  post 'add_players_to_season', to: 'seasons#add_players_to_season'
  resources :players
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :season
  has_and_belongs_to_many :players
  has_many :statistics, through: :players

  accepts_nested_attributes_for :statistics
  def format_date(date)
    month = Date::MONTHNAMES[date.month]
    day = date.day
    year = date.year
    month.to_s + " " + day.to_s + ", " + year.to_s
  end

  def team_at_bats(game = nil)
    plate_appearances = statistics.where(game_id: game).sum(:plate_appearance)
    walks = statistics.where(game_id: game).sum(:walks)
    sac_fly = statistics.where(game_id: game).sum(:sac_fly)
    @at_bats = plate_appearances - (walks + sac_fly)
  end

  def team_runs(game = nil)
    game ? statistics.where(game_id: game).sum(:runs) : statistics.sum(:runs)
  end

  def team_hits(game = nil)
    @hits = game ? statistics.where(game_id: game).sum(:hits) : statistics.sum(:hits)
  end

  def team_rbis(game = nil)
    game ? statistics.where(game_id: game).sum(:rbis) : statistics.sum(:rbis)
  end

  def team_walks(game = nil)
    game ? statistics.where(game_id: game).sum(:walks) : statistics.sum(:walks)
  end

  def team_strikeouts(game = nil)
    game ? statistics.where(game_id: game).sum(:strikeouts) : statistics.sum(:strikeouts)
  end

  def batting_avg
    string = (@hits.to_f / @at_bats.to_f).round(3)
    sprintf('%.3f', string)
  end
  def game_doubles(game)
    doubles_array = []
    game_stats = statistics.where(game_id: game).where("doubles > 0")
    game_stats.map do |stat|
      if stat.doubles > 1
        doubles_array.push("#{Player.find(stat.player_id).last_name}, #{Player.find(stat.player_id).first_name[0]} #{stat.doubles};")
      else stat.doubles = 1
        doubles_array.push("#{Player.find(stat.player_id).last_name}, #{Player.find(stat.player_id).first_name[0]};")
      end
    end
  doubles_array
  end

  def game_triples(game)
    triples_array = []
    game_stats = statistics.where(game_id: game).where("triples > 0")
    game_stats.each do |stat|
      if stat.triples > 1
        triples_array.push("#{Player.find(stat.player_id).last_name}, #{Player.find(stat.player_id).first_name[0]} #{stat.triples};")
      else stat.triples = 1
        triples_array.push("#{Player.find(stat.player_id).last_name}, #{Player.find(stat.player_id).first_name[0]};")
      end
    end
  triples_array
  end

  def game_homers(game)
    homers_array = []
    game_stats = statistics.where(game_id: game).where("homers > 0")
    game_stats.each do |stat|
      if stat.homers > 1
        homers_array.push("#{Player.find(stat.player_id).last_name}, #{Player.find(stat.player_id).first_name[0]} #{stat.homers};")
      else stat.homers = 1
        homers_array.push("#{Player.find(stat.player_id).last_name}, #{Player.find(stat.player_id).first_name[0]};")
      end
    end
  homers_array
  end

  def game_sac_fly(game)
    sac_fly_array = []
    game_stats = statistics.where(game_id: game).where("sac_fly > 0")
    game_stats.each do |stat|
      if stat.sac_fly > 1
        sac_fly_array.push("#{Player.find(stat.player_id).last_name}, #{Player.find(stat.player_id).first_name[0]} #{stat.sac_fly};")
      else stat.sac_fly = 1
        sac_fly_array.push("#{Player.find(stat.player_id).last_name}, #{Player.find(stat.player_id).first_name[0]};")
      end
    end
  sac_fly_array
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def show
    @game = Game.find(params[:id])
    @players = @game.players
    @players.each do |player|
      @player = player
    end
  end

  def new
    @season = Season.find(params[:season_id])
    @game = Game.new(season: @season)
  end

  def create
    @season = Season.find(params[:season_id])
    @game = Game.create(game_params)
    if @game.save
      redirect_to season_game_path(game: @game.id, season: @game.season_id)
    else
      render :new
    end
  end

  def edit
    @game = Game.find(params[:id])
    @season = Season.find(@game.season_id)
  end

  def update
    @game = Game.find(params[:id])
    @game.update(game_params)
    if @game.save
      redirect_to season_game_path(game: @game.id, season: @game.season_id)
    else
      render :edit
    end
  end

  private
  def game_params
    game_params.require(:game).permit(:opponent, :opponent_score, :home_score, statistics_attributes: [:played, :plate_appearance, :runs, :hits, :doubles, :triples, :homers, :rbis, :walks, :hit_by_pitch, :strikeouts, :sac_fly, :player_id ])
  end
end

app/views/games/_extra_stats.html.erb
<div id="extra-stats">
  <b>BATTING</b><br>
<% if @game.game_doubles(@game.id) == [] %>
<% else %>
  <b>2B:</b>
  <% @game.game_doubles(@game.id).each do |player| %>
    <%= player %>
  <% end %>
<% end %>
<% if @game.game_triples(@game.id) == [] %>
<% else %>
  <br><b>3B:</b>
  <% @game.game_triples(@game.id).each do |player| %>
    <%= player %>
  <% end %>
<% end %>
<% if @game.game_homers(@game.id) == [] %>
<% else %>
  <br><b>HR:</b>
  <% @game.game_homers(@game.id).each do |player| %>
    <%= player %>
  <% end %>
<% end %>
<% if @game.game_sac_fly(@game.id) == [] %>
<% else %>
  <br><b>SF:</b>
  <% @game.game_sac_fly(@game.id).each do |player| %>
    <%= player %>
  <% end %>
<% end %>
</div>

app/views/games/_form.html.erb
<%= form_for @game do |f| %>
  <%= f.hidden_field(:season_id, value: @game.season_id) %>
  <%= f.label :opponent  %>
  <%= f.text_field :opponent %>

  <%= f.label :opponent_score %>
  <%= f.number_field :opponent_score %>

  <%= f.label :home_score %>
  <%= f.number_field :home_score %>

  <%= f.fields_for :statistics do |stat| %>
    <%= stat.label :player %>
    <%= stat.collection_select(:player_id, @season.players, :id, :name, {}, multiple: true) %>
    <table>
      <tr>
        <%= stat.number_field :hits, placeholder: 'hits' %>
      </tr>
    </table>
  <% end %>
    <%= f.submit %>
<% end %>

app/views/games/_game_stats.html.erb
<table border="2">
  <thead>
    <tr>
      <th>Moonrakers</th>
      <th>AB</th>
      <th>R</th>
      <th>H</th>
      <th>RBI</th>
      <th>BB</th>
      <th>SO</th>
      <th>AVG</th>
    </tr>
  </thead>
  <tbody>
    <% @game.statistics.each do |stat| %>
      <% if stat.game_id == @game.id %>
        <tr>
          <td><%= link_to(stat.player_name(stat.player_id), player_path(Player.find(stat.player_id)))  %> </td>
          <td><%= stat.at_bats(stat) %></td>
          <td><%= stat.runs %></td>
          <td><%= stat.hits %></td>
          <td><%= stat.rbis %></td>
          <td><%= stat.walks %></td>
          <td><%= stat.strikeouts %></td>
          <td><%= stat.batting_avg(stat.hits) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <thead>
    <tr>
      <th>Totals</th>
      <th><%= @game.team_at_bats(@game) %></th>
      <th><%= @game.team_runs(@game) %></th>
      <th><%= @game.team_hits(@game) %></th>
      <th><%= @game.team_rbis(@game) %></th>
      <th><%= @game.team_walks(@game) %></th>
      <th><%= @game.team_strikeouts(@game) %></th>
      <th><%= @game.batting_avg %></th>
    </tr>
  </thead>
</table>
<%= render "extra_stats" %>

app/views/games/edit.html.erb
<%= render 'form' %>

app/views/games/new.html.erb
<%= render 'form' %>

app/views/games/show.html.erb
<div id="content">
  <% if can? :update, @game %>
    <%= link_to "Edit Game", edit_season_game_path(game: @game.id) %>
  <% end %>
  <table>
    <thead>
      <tr>
        <th><%= @game.format_date(@game.date) %></th>
        <th>1</th>
        <th>2</th>
        <th>3</th>
        <th>4</th>
        <th>5</th>
        <th>6</th>
        <th>7</th>
        <th>8</th>
        <th>9</th>
        <th>R</th>
        <th>H</th>
      </tr>
    </thead>
    <tbody>
      <tr class="opponent">
        <th><%= @game.opponent %></th>
        <td><%= @game.opponent_first_inning  %></td>
        <td><%= @game.opponent_second_inning  %></td>
        <td><%= @game.opponent_third_inning  %></td>
        <td><%= @game.opponent_fourth_inning  %></td>
        <td><%= @game.opponent_fifth_inning  %></td>
        <td><%= @game.opponent_sixth_inning  %></td>
        <td><%= @game.opponent_seventh_inning  %></td>
        <td><%= @game.opponent_eigth_inning  %></td>
        <td><%= @game.opponent_ninth_inning  %></td>
        <td><strong><%= @game.opponent_score %></strong></td>
        <td><strong><%= @game.opponent_score %></strong></td>
      </tr>
      <tr class="moonrakers">
        <th>Moonrakers</th>
        <td><%= @game.home_first_inning  %></td>
        <td><%= @game.home_second_inning  %></td>
        <td><%= @game.home_third_inning  %></td>
        <td><%= @game.home_fourth_inning  %></td>
        <td><%= @game.home_fifth_inning  %></td>
        <td><%= @game.home_sixth_inning  %></td>
        <td><%= @game.home_seventh_inning  %></td>
        <td><%= @game.home_eigth_inning  %></td>
        <td><%= @game.home_ninth_inning  %></td>
        <td><strong><%= @game.home_score %></strong></td>
        <td><strong><%= @game.team_hits(@game) %></strong></td>
      </tr>
    </tbody>
  </table>

  <%= render 'games/game_stats' %>
</div>