config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#team_info'
  get '/all_users', to: 'visitors#all_users'
  devise_for :users
  resources :users
  resources :seasons do
    resources :games, except: [:index]
  end
  post 'add_players_to_season', to: 'seasons#add_players_to_season'
  resources :players
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_and_belongs_to_many :seasons
  has_and_belongs_to_many :games
  has_many :statistics

  def name
    "#{first_name} #{last_name}"
  end

  def full_birthday(date)
    month = Date::MONTHNAMES[date.month]
    day = date.day
    year = date.year
    month.to_s + " " + day.to_s + ", " + year.to_s
  end

  def shorten_birthday(date)
    month = Date::MONTHNAMES[date.month]
    day = date.day
    year = date.year
    month[0..2].to_s + " " + day.to_s + ", " + year.to_s
  end

  def year(array)
    year = array.map do |attribute|
      attribute.season_id
    end
    @year = Season.find(year)[0]
  end

  def total_games(season = nil)
    if season
      total_games ||= statistics.where(season_id: season).count
    else
      total_plate_appearance ||= statistics.count
    end
  end

  def total_plate_appearance(season = nil)
    if season
      total_plate_appearance ||= statistics.where(season_id: season).sum(:plate_appearance)
    else
      total_plate_appearance ||= statistics.sum(:plate_appearance)
    end
  end

  def total_runs(season = nil)
    if season
      total_runs ||= statistics.where(season_id: season).sum(:runs)
    else
      total_runs ||= statistics.sum(:runs)
    end
  end

  def total_hits(season = nil)
    if season
      total_hits ||= statistics.where(season_id: season).sum(:hits)
    else
      total_hits ||= statistics.sum(:hits)
    end
  end

  def total_doubles(season = nil)
    if season
      total_doubles ||= statistics.where(season_id: season).sum(:doubles)
    else
      total_doubles ||= statistics.sum(:doubles)
    end
  end

  def total_triples(season = nil)
    if season
      total_triples ||= statistics.where(season_id: season).sum(:triples)
    else
      total_triples ||= statistics.sum(:triples)
    end
  end

  def total_homers(season = nil)
    if season
      total_homers ||= statistics.where(season_id: season).sum(:homers)
    else
      total_homers ||= statistics.sum(:homers)
    end

  end

  def total_rbis(season = nil)
    if season
      total_rbis ||= statistics.where(season_id: season).sum(:rbis)
    else
      total_rbis ||= statistics.sum(:rbis)
    end
  end

  def total_walks(season = nil)
    if season
      total_walks ||= statistics.where(season_id: season).sum(:walks)
    else
      total_walks ||= statistics.sum(:walks)
    end
  end

  def total_strikeouts(season = nil)
    if season
      total_strikeouts ||= statistics.where(season_id: season).sum(:strikeouts)
    else
      total_strikeouts ||= statistics.sum(:strikeouts)
    end
  end

  def total_sac_fly(season = nil)
    if season
      total_sac_fly ||= statistics.where(season_id: season).sum(:sac_fly)
    else
      total_sac_fly ||= statistics.sum(:sac_fly)
    end
  end

  def total_at_bats(season = nil)
    if season
      total_at_bats ||= statistics.where(season_id: season).sum(:plate_appearance) - (statistics.where(season_id: season).sum(:walks) + statistics.where(season_id: season).sum(:sac_fly))
    else
      total_at_bats ||= statistics.sum(:plate_appearance) - (statistics.sum(:walks) + statistics.sum(:sac_fly))
    end
  end

  def season_batting_avg(season = nil)
    if season
      string = (statistics.where(season_id: season).sum(:hits).to_f / (statistics.where(season_id: season).sum(:plate_appearance) - (statistics.where(season_id: season).sum(:walks) + statistics.where(season_id: season).sum(:sac_fly))).to_f).round(3)
      sprintf('%.3f', string)
    else
      string = (total_hits.to_f / total_at_bats.to_f).round(3)
      sprintf('%.3f', string)
    end
  end

  def total_bases(season = nil)
    if season
      hits = statistics.where(season_id: season).sum(:hits)
      doubles = statistics.where(season_id: season).sum(:doubles)
      triples = statistics.where(season_id: season).sum(:triples)
      homers = statistics.where(season_id: season).sum(:homers)
      singles = (hits - (doubles + triples + homers))
      @total_bases = singles + (2 * doubles) + (3 * triples) + (4 * homers)
    else
      hits = statistics.sum(:hits)
      doubles = statistics.sum(:doubles)
      triples = statistics.sum(:triples)
      homers = statistics.sum(:homers)
      singles = (hits - (doubles + triples + homers))
      @total_bases = singles + (2 * doubles) + (3 * triples) + (4 * homers)
    end
  end

  def on_base_pct(season = nil)
    if season
      season_hits = statistics.where(season_id: season).sum(:hits)
      season_walks = statistics.where(season_id: season).sum(:walks)
      season_sac_fly = statistics.where(season_id: season).sum(:sac_fly)
      season_at_bats = statistics.where(season_id: season).sum(:plate_appearance) - (statistics.where(season_id: season).sum(:walks) + statistics.where(season_id: season).sum(:sac_fly))
      @on_base_pct = ((season_hits.to_f + season_walks.to_f) / (season_at_bats.to_f + season_walks.to_f + season_sac_fly.to_f)).round(3)
      sprintf('%.3f', @on_base_pct)
    else
      hits = statistics.sum(:hits)
      walks = statistics.sum(:walks)
      sac_fly = statistics.sum(:sac_fly)
      at_bats = statistics.sum(:plate_appearance) - (statistics.sum(:walks) + statistics.sum(:sac_fly))
      @on_base_pct = ((hits.to_f + walks.to_f) / (at_bats.to_f + walks.to_f + sac_fly.to_f)).round(3)
      sprintf('%.3f', @on_base_pct)
    end
  end

  def slugging_pct(season = nil)
    if season
      at_bats = statistics.where(season_id: season).sum(:plate_appearance) - (statistics.where(season_id: season).sum(:walks) + statistics.where(season_id: season).sum(:sac_fly))
      @slugging_pct = (@total_bases.to_f / at_bats.to_f).round(3)
      sprintf('%.3f', @slugging_pct)
    else
      at_bats = statistics.sum(:plate_appearance) - (statistics.sum(:walks) + statistics.sum(:sac_fly))
      @slugging_pct = (@total_bases.to_f / at_bats.to_f).round(3)
      sprintf('%.3f', @slugging_pct)
    end
  end

   def on_base_plus_slg
     @on_base_plus_slug = @slugging_pct + @on_base_pct
     sprintf('%.3f', @on_base_plus_slug)
   end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.all
    @seasons = Season.all
  end

  def show
    @player = Player.find(params[:id])
    @seasons = Season.all
    @statistics = Statistic.all
  end

  def new
    @player = Player.new
    @primary_positions = ["P","C", "1B", "2B", "3B", "SS", "LF", "CF", "RF", "SC"]
    @position_descriptions = ["Pitchers", "Catchers", "Infielders", "Outfielders"]
    @bats = ["L","R","S"]
    @throws = ["L","R"]
  end

  def create
    @player = Player.create(player_params)
    if @player.save
      redirect_to player_path(@player)
    else
      render :new
    end
  end

  def edit
    @player = Player.find(params[:id])
    @primary_positions = ["P","C", "1B", "2B", "3B", "SS", "LF", "CF", "RF", "SC"]
    @position_descriptions = ["Pitchers", "Catchers", "Infielders", "Outfielders"]
    @bats = ["L","R","S"]
    @throws = ["L","R"]
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(player_params)
      redirect_to player_path(@player)
    else
      render :edit
    end
  end

  def destroy
    @player = Player.find(params[:id])
    if @player.destroy
      redirect_to players_path
    else
      redirect_to player_path
    end
  end

  private
  def player_params
    params.require(:player).permit(:first_name, :last_name, :number, :primary_position, :secondary_position, :position_description, :bats, :throws, :photo, :description, :height, :weight, :birthday)
  end

end

app/views/players/_catchers.html.erb
<% @players.each do |player| %>
  <% if player.position_description == "Catchers" %>
    <tr>
      <td class="number"><%= player.number %></td>
      <td class="first-name"><%= link_to (player.first_name + " " + player.last_name), player_path(player) %></td>
      <td class="bats"><%= player.bats %></td>
      <td class="throws"><%= player.throws %></td>
      <td class="height"><%= player.height %>"</td>
      <td class="weight"><%= player.weight %>lbs</td>
      <td class="birthday"><%= player.shorten_birthday(player.birthday) %></td>
    </tr>
  <% end %>
<% end %>

app/views/players/_form.html.erb
<%= form_for @player do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :number %>
  <%= f.number_field :number %>

  <%= f.label :primary_position %>
  <%= f.select :primary_position, options_for_select(@primary_positions.map {|primary_position| primary_position }) %>

  <%= f.label :secondary_position %>
  <%= f.select :secondary_position, options_for_select(@primary_positions.map {|primary_position| primary_position }) %>

  <%= f.label :position_description %>
  <%= f.select :position_description, options_for_select(@position_descriptions.map {|position_description| position_description}) %>

  <%= f.label :bats %>
  <%= f.select :bats, options_for_select(@bats.map{|bat| bat}) %>

  <%= f.label :throws %>
  <%= f.select :throws, options_for_select(@throws.map{|throw| throw}) %>

  <%= f.label :photo %>
  <%= f.text_field :photo %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :height %>
  <%= f.text_field :height %>

  <%= f.label :weight %>
  <%= f.number_field :weight %>

  <%= f.label :birthday %>
  <%= f.date_field :birthday %>

  <%= f.submit %>
<% end %>

app/views/players/_infielders.html.erb
<% @players.each do |player| %>
  <% if player.position_description == "Infielders" %>
    <tr>
      <td class="number"><%= player.number %></td>
      <td class="first-name"><%= link_to (player.first_name + " " + player.last_name), player_path(player) %></td>
      <td class="bats"><%= player.bats %></td>
      <td class="throws"><%= player.throws %></td>
      <td class="height"><%= player.height %>"</td>
      <td class="weight"><%= player.weight %>lbs</td>
      <td class="birthday"><%= player.shorten_birthday(player.birthday) %></td>
    </tr>
  <% end %>
<% end %>

app/views/players/_outfielders.html.erb
<% @players.each do |player| %>
  <% if player.position_description == "Outfielders" %>
    <tr>
      <td class="number"><%= player.number %></td>
      <td class="first-name"><%= link_to (player.first_name + " " + player.last_name), player_path(player) %></td>
      <td class="bats"><%= player.bats %></td>
      <td class="throws"><%= player.throws %></td>
      <td class="height"><%= player.height %>"</td>
      <td class="weight"><%= player.weight %>lbs</td>
      <td class="birthday"><%= player.shorten_birthday(player.birthday) %></td>
    </tr>
  <% end %>
<% end %>

app/views/players/_pitchers.html.erb
<% @players.each do |player| %>
  <% if player.position_description == "Pitchers" %>
    <tr>
      <td class="number"><%= player.number %></td>
      <td class="first-name"><%= link_to (player.first_name + " " + player.last_name), player_path(player) %></td>
      <td class="bats"><%= player.bats %></td>
      <td class="throws"><%= player.throws %></td>
      <td class="height"><%= player.height %>"</td>
      <td class="weight"><%= player.weight %>lbs</td>
      <td class="birthday"><%= player.shorten_birthday(player.birthday) %></td>
    </tr>
  <% end %>
<% end %>

app/views/players/_total_player_stats.html.erb
<tbody>
  <% @player.seasons.order(year: :asc).each do |season| %>
    <tr>
      <td><%= link_to season.year, season_path(season) %></td>
      <td><%= @player.total_games(season.id) %></td>
      <td><%= @player.total_plate_appearance(season.id) %></td>
      <td><%= @player.total_at_bats(season.id) %></td>
      <td><%= @player.total_runs(season.id) %></td>
      <td><%= @player.total_hits(season.id) %></td>
      <td><%= @player.total_doubles(season.id) %></td>
      <td><%= @player.total_triples(season.id) %></td>
      <td><%= @player.total_homers(season.id) %></td>
      <td><%= @player.total_rbis(season.id) %></td>
      <td><%= @player.total_walks(season.id) %></td>
      <td><%= @player.total_strikeouts(season.id) %></td>
      <td><%= @player.total_sac_fly(season.id) %></td>
      <td><%= @player.total_bases(season.id) %></td>
      <td><%= @player.season_batting_avg(season.id) %></td>
      <td><%= @player.on_base_pct(season.id)  %></td>
      <td><%= @player.slugging_pct(season.id)  %></td>
      <td><%= @player.on_base_plus_slg %></td>
    </tr>
  <% end %>
  <tr class="last">
    <td>Totals</td>
    <td><%= @player.statistics.count %></td>
    <td><%= @player.total_plate_appearance %></td>
    <td><%= @player.total_at_bats %></td>
    <td><%= @player.total_runs %></td>
    <td><%= @player.total_hits %></td>
    <td><%= @player.total_doubles %></td>
    <td><%= @player.total_triples %></td>
    <td><%= @player.total_homers %></td>
    <td><%= @player.total_rbis %></td>
    <td><%= @player.total_walks %></td>
    <td><%= @player.total_strikeouts %></td>
    <td><%= @player.total_sac_fly %></td>
    <td><%= @player.total_bases %></td>
    <td><%= @player.season_batting_avg %></td>
    <td><%= @player.on_base_pct  %></td>
    <td><%= @player.slugging_pct  %></td>
    <td><%= @player.on_base_plus_slg %></td>
  </tr>
</tbody>

app/views/players/edit.html.erb
<%= render 'form' %>
<% if can? :destroy, @player %>
  <%= link_to "Delete", player_path(@player), method: :delete  %>
<% end %>

app/views/players/index.html.erb
<div id="content">
  <% if can? :create, @player %>
    <%= link_to "Add Player", new_player_path(@player) %>
  <% end %>

  <h2 class="title">Roster</h2>
  <table class="roster" border="2">
    <thead class="pitchers">
      <tr>
        <th>#</th>
        <th>Pitchers</th>
        <th>Bats</th>
        <th>Throws</th>
        <th>Height</th>
        <th>Weight</th>
        <th>DOB</th>
      </tr>
    </thead>
    <tbody>
      <%= render 'players/pitchers' %>
    </tbody>
    <thead class="catchers">
      <tr>
        <th>#</th>
        <th>Catchers</th>
        <th>Bats</th>
        <th>Throws</th>
        <th>Height</th>
        <th>Weight</th>
        <th>DOB</th>
      </tr>
    </thead>
    <tbody>
      <%= render 'players/catchers' %>
    </tbody>
    <thead class="infielders">
      <tr>
        <th>#</th>
        <th>Infielders</th>
        <th>Bats</th>
        <th>Throws</th>
        <th>Height</th>
        <th>Weight</th>
        <th>DOB</th>
      </tr>
    </thead>
    <tbody>
      <%= render 'players/infielders' %>
    </tbody>
    <thead class="outfielders">
      <tr>
        <th>#</th>
        <th>Outfielders</th>
        <th>Bats</th>
        <th>Throws</th>
        <th>Height</th>
        <th>Weight</th>
        <th>DOB</th>
      </tr>
    </thead>
    <tbody>
      <%= render 'players/outfielders' %>
    </tbody>
  </table>
</div>

app/views/players/show.html.erb
<div class="scrolls">
  <div id="content">
    <% if can? :update, @player %>
      <%= link_to "Edit Player", edit_player_path(@player) %>
    <% end %>
    <div id="player-card">
      <div id="photo">
        <%= image_tag(@player.photo) %>
      </div>
      <div id="main-name">
        <h1 id="player-name">
          <%= @player.first_name + " " + @player.last_name %>
          <span id="player-number"><%= @player.number %> |</span>
          <span id="player-position"><%= @player.primary_position %></span>
        </h1>
      </div>
      <div id="player-info">
        <p>
          <strong>Born:</strong> <%= @player.full_birthday(@player.birthday) %><br>
          <strong>Bats/Throws:</strong> <%= @player.bats %>/<%= @player.throws %><br>
          <strong>Height:</strong> <%= @player.height %>"
          <strong>Weight:</strong> <%= @player.weight %>
        </p>
      </div>
    </div>
    <% if @player.statistics == [] %>
      <%= "" %>
    <% else %>

    <div id="player-stats">
      <div class="head">
        <td><%= @player.name %> Career Stats</td>
      </div>
      <table border="2">
        <%= render 'seasons/season_stats_header' %>
        <%= render 'total_player_stats' %>
      </table>
    </div>
    <% end %>
  </div>
</div>