config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#team_info'
  get '/all_users', to: 'visitors#all_users'
  devise_for :users
  resources :users
  resources :seasons do
    resources :games, except: [:index]
  end
  post 'add_players_to_season', to: 'seasons#add_players_to_season'
  resources :players
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li class="Logo"><%= link_to 'Moonrakers', root_path %></li>
  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to "Roster", players_path %></li>
  <li><%= link_to "Seasons", seasons_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to "Roster", players_path %></li>
  <li><%= link_to "Seasons", seasons_path %></li>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Moonraker" %></title>
    <link href='http://fonts.googleapis.com/css?family=Seaweed+Script' rel='stylesheet' type='text/css'>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Moonraker" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      <%= render 'layouts/messages' %>
      <%= yield %>
  </body>
</html>